# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "1StrongPwd!!"